# Generated by Django 3.1.4 on 2020-12-11 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple21', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('''CREATE UNIQUE INDEX page_tree_must_have_only_one_root ON simple21_page ((1)) WHERE parent_id IS NULL;''')
    ]
