# Generated by Django 3.0.4 on 2020-04-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple21', '0003_globalconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='type',
        ),
        migrations.AddField(
            model_name='term',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='url',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
