# Generated by Django 3.0.4 on 2020-04-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple21', '0004_auto_20200402_2028'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='term',
            constraint=models.CheckConstraint(check=models.Q(('parent__isnull', False), ('slug', 'root'), _connector='OR'), name='parent_must_exist__or__is_root'),
        ),
    ]
